[package]
name = "rust-study-sort"
version = "0.1.0"
authors = ["Satoru Sukawa <sukawasatoru.github@outlook.jp>"]

[dependencies]
log = "0.4.1"
env_logger = "0.5.6"
serde = "1.0.36"
serde_derive = "1.0.36"
serde_json = "1.0.13"
